# Generated by Django 3.1 on 2021-03-09 19:41

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False,),),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title'),),
            ],
            options={'db_table': 'movies_genre'},
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False,),),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name'),),
            ],
            options={'db_table': 'movies_person'},
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False,),),
                ('title', models.CharField(max_length=255, verbose_name='Title'),),
                ('is_suspicious', models.BooleanField(default=False, verbose_name='Is suspicious movie'),),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description'),),
                (
                    'imdb_rating',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='IMDB rating',
                    ),
                ),
                (
                    'actors',
                    models.ManyToManyField(
                        db_table='movies_movie_actors',
                        related_name='movies_acted',
                        to='movies.Person',
                        verbose_name='Actors',
                    ),
                ),
                (
                    'directors',
                    models.ManyToManyField(
                        db_table='movies_movie_directors',
                        related_name='movies_directed',
                        to='movies.Person',
                        verbose_name='Directors',
                    ),
                ),
                (
                    'genres',
                    models.ManyToManyField(
                        db_table='movies_movie_genres', related_name='movies', to='movies.Genre', verbose_name='Genres',
                    ),
                ),
                (
                    'writers',
                    models.ManyToManyField(
                        db_table='movies_movie_writers',
                        related_name='movies_written',
                        to='movies.Person',
                        verbose_name='Writers',
                    ),
                ),
            ],
            options={'db_table': 'movies_movie'},
        ),
    ]
