# Generated by Django 3.1 on 2021-03-19 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('movies', '0001_initial')]

    operations = [
        migrations.AlterModelOptions(name='genre', options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},),
        migrations.AlterModelOptions(
            name='movie', options={'ordering': ('-title',), 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies',},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('last_name',), 'verbose_name': 'Person', 'verbose_name_plural': 'People',},
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='movie',
            name='age_rating',
            field=models.FloatField(
                blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rating',
            ),
        ),
        migrations.AddField(
            model_name='movie',
            name='certificate',
            field=models.TextField(blank=True, null=True, verbose_name='Certificate'),
        ),
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, null=True, verbose_name='Date of publication',
            ),
        ),
        migrations.AddField(
            model_name='movie',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of creation'),
        ),
        migrations.AddField(
            model_name='movie',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='film_works/', verbose_name='File',),
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(
                choices=[('movie', 'Film'), ('tv_show', 'Show')], default='movie', max_length=20, verbose_name='Type',
            ),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First name',),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='IMDB rating',
            ),
        ),
    ]
