# Generated by Django 3.1 on 2021-03-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('movies', '0002_update_existing_tables_to_fit_movies_models')]

    operations = [
        migrations.AddField(model_name='genre', name='updated_at', field=models.DateTimeField(auto_now=True),),
        migrations.AddField(model_name='movie', name='updated_at', field=models.DateTimeField(auto_now=True),),
        migrations.AddField(model_name='person', name='updated_at', field=models.DateTimeField(auto_now=True),),
    ]
