# Generated by Django 3.1 on 2021-07-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_add_index_to_updated_at_field_to_all_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_suspicious',
            field=models.BooleanField(default=False, verbose_name='Is suspicious'),
        ),
    ]
